### ISSUE TITLE
BUG: netcdf4 conversion error in forecast.py 

### ISSUE THREAD

**Issue by CameronTStark** [pvlib/pvlib-python#944] opened 2020-03-27 20:48 UTC
**Describe the bug**
The method `get_data()` from the parent class `ForecastModel` has a handling NETCDF data. It produces the following error on multiple tests within `test_forecast.py`:

`TypeError: <class 'cftime._cftime.DatetimeGregorian'> is not convertible to datetime`

**To Reproduce**
Run the command locally:

`pytest pvlib/tests/test_forecast.py --remote-data --pdb` 

This command will ensure the tests marked as `remote_data` are run and you'll be dropped into a pdb debugger.

**Expected behavior**
The formatted data would be received without error.

**Screenshots**

**Versions:**
 - ``pvlib.__version__``: 0.7.1 master
 - ``pandas.__version__``: 1.0.3
 - python: 3.7.4

**Additional context**
I'm unsure about the underlying origin but the disconnect seems to come through `get_data()` -> `_netcdf2pandas()` -> `set_time()` where `num2date` supplies a DatetimeGregorian that Pandas can't process. 

It's notable that there is a suggestion on line 279 of forecast.py about the potential to move to xarray's implementation of NetCDF rather than using the `_netcdf2pandas()` method. This avenue likely has the potential to be easier than continuing a pvlib implementation.

**Comment by wholmgren** [comment] 2020-03-28 02:31
Duplicate of #920?

**Comment by CameronTStark** [comment] 2020-03-28 03:18
I don't think so but I can't say they're not related. 

The error described in #920 is not the same as here nor does the solution proposed in #921 fix this issue.

**Comment by kanderso-nrel** [comment] 2020-03-28 03:34
FWIW I cannot reproduce the errors on my machine.  

Maybe not relevant, but just in case:  #900 handled the cftime change that added `only_use_cftime_datetimes`, but there was another recent change to add `only_use_python_datetimes`: https://github.com/Unidata/cftime/pull/139/files#diff-9225bec7bdd479a2dfbc187bb72953d1R259

**Comment by augustecolle** [comment] 2020-03-28 20:40
Downgrading cftime solved this issue for me.

**Comment by CameronTStark** [comment] 2020-03-28 21:18
That did it for me. Thanks, @augustecolle!

**Comment by wholmgren** [comment] 2020-03-30 15:44
@CameronTStark do you still see this problem when using pvlib/pvlib-python/master? I think @kanderso-nrel's suggestion might have fixed it and #947 might be unnecessary. Sorry I got confused about which issue to reference.

**Closed** 2020-04-13 15:24 UTC
Labels: bug
