### ISSUE TITLE
CEC module library is behind current version in SAM (2022)

### ISSUE THREAD

**Issue by LucaNicoliYT88** [pvlib/pvlib-python#1571] opened 2022-10-13 13:05 UTC
Ciao, 

if I check the version of the CEC Modules in SAM library, the file is updated at 5/28/2022.
If I check the versione of the same DB in pvlib, the version is with the date 3/1/2019.

Is it possibile to update the file in pvlib?

Thanks.

**Comment by kanderso-nrel** [comment] 2022-10-13 13:57
Copy/pasting my response in the google group:

> It is on our to-do list to update the library included in pvlib.  Until then you can use the updated file from the SAM github repository.  They keep the file in "/deploy/libraries/", and you can import that latest one into pvlib with a URL like this:
>
> `df = pvlib.pvsystem.retrieve_sam(path='https://github.com/NREL/SAM/raw/develop/deploy/libraries/CEC%20Modules.csv')`
>
> You can also download that file with your web browser and specify a local filepath in "retrieve_sam", if you prefer.

I'm going to close this since it's a duplicate of #1345.

**Closed by kanderso-nrel** 2022-10-13 13:57 UTC
