### ISSUE TITLE
Read The Docs not rendering API arguments : types correctly

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#690] opened 2019-04-22 18:24 UTC
**Describe the bug**
there is no colon between args and types anymore

**Screenshots**
https://pvlib-python.readthedocs.io/en/latest/generated/pvlib.location.Location.get_solarposition.html#pvlib.location.Location.get_solarposition
![image](https://user-images.githubusercontent.com/1385621/56517063-e21d2400-64f0-11e9-83f2-cb8a1ff21da2.png)

**Expected behavior**
there should be colons, like this
https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.location.Location.get_solarposition.html
![image](https://user-images.githubusercontent.com/1385621/56517159-21e40b80-64f1-11e9-9133-7bed5d577e18.png)

**Comment by wholmgren** [comment] 2019-04-22 18:44
The "expected behavior" also looks bad because there's no space between the colons and the types. I'm guessing this is due to numpydoc or the sphinxrtd theme (or both). I saw there's a new numpydoc release so I manually triggered the doc build. Unfortunately there now an error that prevents the build from completing. See here: https://readthedocs.org/projects/pvlib-python/builds/8948978/

**Comment by mikofski** [comment] 2019-04-22 22:03
From the error I think it's because the ["see also" items in `solar_zenith_analytical`](../blob/ef82a39/pvlib/solarposition.py#L1300) are all on the same line without commas. I think I should have put them on separate lines.

**Comment by mikofski** [comment] 2019-04-23 08:09
Okay, I think I got it working, needed `sphinx.ext.napoleon` extension, see [this blogger](https://samnicholls.net/2016/06/15/how-to-sphinx-readthedocs/)

![image](https://user-images.githubusercontent.com/1385621/56565077-68268280-6564-11e9-9ce6-3653cdccdb81.png)


much better, right? there are a couple of options you can read about them here in [napoleon docs](http://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#configuration), numpydoc is enabled by default. I played around with them, but I couldn't really see any differences.

**Comment by wholmgren** [comment] 2019-04-24 14:27
The "latest" docs are building successfully, so I'll close this.

<img width="761" alt="Screen Shot 2019-04-24 at 7 26 21 AM" src="https://user-images.githubusercontent.com/4383303/56667250-5925fa00-6662-11e9-9e94-5d858eff51e8.png">

**Closed by wholmgren** 2019-04-24 14:27 UTC
