### ISSUE TITLE
Std. deviation of slope is calculated incorrectly for clearsky.detect_clearsky

### ISSUE THREAD

**Issue by cwhanse** [pvlib/pvlib-python#1241] opened 2021-06-04 16:16 UTC
**Describe the bug**

[This line](https://github.com/pvlib/pvlib-python/blob/82208ff8f26af52fd77ed3bdc030e68bfd0ed265/pvlib/clearsky.py#L644)

```
raw = np.diff(data)
```

does not calculate the slope since it is not divided by the time interval.

**Expected behavior**

```
raw = np.diff(data) / sample_interval

```
**Versions:**
 - ``pvlib.__version__``: 0.8.1

**Additional context**

All current tests use 1-minute intervals, so the tests are not incorrect.

**Comment by wholmgren** [comment] 2021-06-04 16:23
from looking at the title only... is this a duplicate of #1070?

**Comment by cwhanse** [comment] 2021-06-04 16:28
No. #1070 can be closed with some comments in the code to explain the deviation from the reference.

**Closed** 2021-06-25 22:56 UTC
